version: '3'
services:
  redis-server:
    image: 'redis'
    expose:
      - '6379'
  postgresdb:
    image: postgres:14
    container_name: postgres_container
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./Docker/init.sh:/docker-entrypoint-initdb.d/0-init-user-db.sh
      - ./Docker/init/db.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./Docker/init/seeding.sql:/docker-entrypoint-initdb.d/2-seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$DB_USER -d $$DB_NAME"]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - '5432'
  itrex-project:
    build: .
    depends_on:
      postgresdb :
          condition: service_healthy
    restart: always
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - PORT=3000
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - DB_HOST=postgresdb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$PG_DOCKER_PORT
      - JWT_SECRET=$JWT_SECRET
